name: Code Review 
on:
  # Triggers the workflow on pull request events but only for the "main" branch
  pull_request:
    branches: [ "main" ]

jobs:
  check-quality:
    runs-on: ubuntu-latest
    name: A job to check my code quality
    steps:
    - uses: actions/checkout@v2
    - uses: microsoft/ApplicationInspector-Action@v1
    - uses: actions/upload-artifact@v2
      with:
        name: AppInspectorResults
        path: AppInspectorResults.json
